### ISSUE TITLE
Add hover text to the message type icons

### ISSUE THREAD

**Issue by mjbvz** [Microsoft/language-server-protocol-inspector#24]
https://github.com/Microsoft/vscode/issues/52866

**Feature request**
Add hover text to the message type icons in the inspector:

![screen shot 2018-06-26 at 4 02 38 pm](https://user-images.githubusercontent.com/12821956/41944013-b73365ba-795a-11e8-8005-eec85cf5c103.png)

The meaning of these icons is already documented on the `usage` page. We should also show this information inline if possible

**Comment by octref** [comment]
I think this is enough hint now:

![image](https://user-images.githubusercontent.com/4033249/42617047-f1553eb4-85e2-11e8-94fe-07f604cae888.png)
