### ISSUE TITLE
Log Format in README.md up-to-date? 

### ISSUE THREAD

**Issue by catlan** [Microsoft/language-server-protocol-inspector#39]
I tried to generate a log file based on the Log Format in README.md. But when I try to upload the sample I only get "No Matching Message". 

Would appreciate any details.

[test.log](https://github.com/Microsoft/language-server-protocol-inspector/files/2761470/test.log)

**Comment by octref** [comment]
Man sorry, have been busy with other things. I'll take a look.

**Comment by octref** [comment]
Take a look at the *.log files for format. The descriptions on README is for illustrative purposes and are not complete.

https://github.com/Microsoft/language-server-protocol-inspector/tree/master/lsp-inspector/tests/unit/logParser/fixture
